### PR TITLE
Feature/flexible report dates

### PR DESCRIPTION
**Pull request by neumanrq**
* minor refactorings of reporting mechanism
* provides `report`method of `Eventable` as public methods to regenerate reports afterwards on demand

### CODE REVIEW

**Comment by cseydel** [comment]
uhh, robin war fleißig.

**Comment by neumanrq** [comment]
Frühjahrsputz, Christoph ;)

**Comment by cseydel** [comment]
Frühjahrsputz in your nose! (in your face schien mir nicht genau genug.) :D

**Comment by neumanrq** [comment]
:nose: 
:point_up:

**Pull request merged**
